spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbappqa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'